#!/bin/bash

# ================================
# BlockExt 최신 코드 반영 배포 스크립트
# ================================

# 루트 디렉터리
ROOT_DIR="/home/ec2-user/blockext/BlockExt"
BACKEND_DIR="$ROOT_DIR/backend"
FRONTEND_DIR="$ROOT_DIR/frontend"

echo "=== BlockExt 배포 시작 ==="

# 1. 최신 코드 가져오기
echo "[1/5] Git 최신 코드 가져오기..."
cd $ROOT_DIR || { echo "루트 디렉터리 이동 실패"; exit 1; }
git fetch --all
git reset --hard
git pull origin main
echo "✅ Git 업데이트 완료"

# 2. 백엔드 빌드
echo "[2/5] 백엔드 빌드 시작..."
cd $BACKEND_DIR || { echo "백엔드 디렉터리 이동 실패"; exit 1; }
chmod +x gradlew
./gradlew clean build -x test
echo "✅ 백엔드 빌드 완료"

# 3. 백엔드 서비스 재시작
echo "[3/5] 백엔드 서비스 재시작..."
sudo systemctl restart backend
echo "✅ 백엔드 서비스 재시작 완료"

# 4. 프론트엔드 빌드
echo "[4/5] 프론트엔드 빌드 시작..."
cd $FRONTEND_DIR || { echo "프론트엔드 디렉터리 이동 실패"; exit 1; }
npm install
npm run build
echo "✅ 프론트엔드 빌드 완료"

# 5. 프론트엔드 서비스 재시작
echo "[5/5] 프론트엔드 서비스 재시작..."
sudo systemctl restart frontend
echo "✅ 프론트엔드 서비스 재시작 완료"

echo "=== BlockExt 배포 완료 ==="
