name: Deploy BlockExt to EC2

on:
  push:
    branches:
      - main   # main 브랜치 푸시 시 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy project to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "."
        target: "/home/ec2-user/blockext"

    - name: Deploy on EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ec2-user/blockext/BlockExt/backend
          chmod +x gradlew
          ./gradlew build -x test
          pkill -f "backend-0.0.1-SNAPSHOT.jar" || true
          nohup java -jar build/libs/*SNAPSHOT.jar > backend.log 2>&1 &

          cd /home/ec2-user/blockext/BlockExt/frontend
          npm install
          pkill -f "react-scripts start" || true
          nohup npm start > frontend.log 2>&1 &
