name: Deploy BlockExt to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 루트 디렉터리 설정
            ROOT_DIR="/home/ec2-user/blockext/BlockExt"
            BACKEND_DIR="$ROOT_DIR/backend"
            FRONTEND_DIR="$ROOT_DIR/frontend"

            echo "=== BlockExt 배포 시작 ==="

            # 최신 코드 가져오기
            cd $ROOT_DIR
            git fetch --all
            git reset --hard
            git pull origin main

            # 백엔드 빌드 및 서비스 재시작
            cd $BACKEND_DIR
            chmod +x gradlew
            ./gradlew clean build -x test
            sudo systemctl restart backend

            # 프론트엔드 빌드 및 서비스 재시작
            cd $FRONTEND_DIR
            npm install
            npm run build
            sudo systemctl restart frontend

            echo "=== BlockExt 배포 완료 ==="
