name: Deploy BlockExt to EC2

on:
  push:
    branches:
      - main   # main 브랜치 푸시 시 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy project to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/home/ec2-user/blockext"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            cd /home/ec2-user/blockext/BlockExt/backend
            echo "Cleaning previous build..."
            ./gradlew clean
            echo "Building backend..."
            ./gradlew build -x test
            echo "Restarting backend service..."
            sudo systemctl restart backend
            sudo systemctl status backend --no-pager

            cd /home/ec2-user/blockext/BlockExt/frontend
            echo "Cleaning previous frontend build..."
            rm -rf build node_modules
            echo "Installing dependencies..."
            npm install
            echo "Building frontend..."
            npm run build
            echo "Restarting frontend service..."
            sudo systemctl restart frontend
            sudo systemctl status frontend --no-pager

            echo "Deployment complete!"
